baseURL = "https://blog.depechie.com/"
languageCode = "en-us"
title = "Depechie’s outing"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.
publishDir = "docs"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "" 

# Add your Disqus shortname here.
disqusShortname = ""    

[taxonomies]
  tag = "tags"

[author]
	name = "Glenn Versweyveld"

[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = true
      tabWidth = 4
      noClasses = false
      style = 'solarized-dark'

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
  unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "‘SH10151’ this is the serial number of our orbital gun"

    showReadMore = true

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	# email = "#"
  # facebook = "#"
  # twitter = "https://twitter.com/depechie"
  mastodon = "https://dotnet.social/@depechie"
	# instagram = "#"
	# tumblr = "#"
	# reddit = "#"
	# pinterest = "#"
	# youtube = "#"
  # vimeo = "#"
	# weibo = "#"
	# vk = "#"
	linkedin = "https://www.linkedin.com/in/depechie/"

	# Writing
  # medium = "#"
	# blogger = "#"
	# wordpress = "#"

	# Creative & Visual
  # dribbble = "#"
	# behance = "#"
	# deviantart = "#"
	# flickr = "#"

  # Audio & Music
  # soundcloud = "#"

	# Programming
  github = "https://github.com/Depechie"
	stackoverflow = "https://stackoverflow.com/users/613087/depechie"
	# gitlab = "#"
	# codepen = "#"

  # Academic
  # googlescholar = "#"
  # impactstory = "#"
  # orcid = "#"  

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 1

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/archives/"
	weight = 2

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true